// eslint-disable-next-line no-unused-vars
module.exports.data = {
  product: "40348",
  page: 0,
  count: 100,
  results: [
    {
      review_id: 1275700,
      rating: 5,
      summary: "",
      recommend: true,
      response: null,
      body: "asdfjkalsdfjklasfjklasfjkla;sdfjklasdaaasdfkjasdfkla",
      date: "2022-07-19T00:00:00.000Z",
      reviewer_name: "asfjklasdfj",
      helpfulness: 0,
      photos: [
        {
          id: 2455558,
          url: "http://res.cloudinary.com/dxhzukgow/image/upload/v1658268200/lapyozl6ct1z5jk9iysx.png",
        },
        {
          id: 2455559,
          url: "http://res.cloudinary.com/dxhzukgow/image/upload/v1658268200/mrskdmh3ybaezylgg5tt.png",
        },
      ],
    },
    {
      review_id: 1275697,
      rating: 5,
      summary: "",
      recommend: false,
      response: null,
      body: "asdfasdfaklsjfklajwekrjaopisdfjoiqawjeriojaskldfjaoeirj",
      date: "2022-07-19T00:00:00.000Z",
      reviewer_name: "asdf",
      helpfulness: 0,
      photos: [],
    },
    {
      review_id: 1275528,
      rating: 5,
      summary: "I might as well be drinking Red Bull...",
      recommend: true,
      response: null,
      body: "... because these shoes make me feel like I can fly!  I believe I can fly. I believe I can touch the sky. I think about it every night and day.  I spread my wings and fly away!",
      date: "2022-07-17T00:00:00.000Z",
      reviewer_name: "bugs bunny",
      helpfulness: 0,
      photos: [
        {
          id: 2455434,
          url: "http://res.cloudinary.com/dxhzukgow/image/upload/v1658101985/podwynqjvh8akjomhz5n.png",
        },
        {
          id: 2455435,
          url: "http://res.cloudinary.com/dxhzukgow/image/upload/v1658101985/kmdmc0zjqrdaifil5tmw.webp",
        },
      ],
    },
    {
      review_id: 1275233,
      rating: 5,
      summary: "MY name is Trey",
      recommend: true,
      response: null,
      body: "My name is trey and i got a basketball game tommorrow",
      date: "2022-06-08T00:00:00.000Z",
      reviewer_name: "Trey",
      helpfulness: 3,
      photos: [
        {
          id: 2455213,
          url: "http://res.cloudinary.com/thejoebro/image/upload/v1654147335/o8v99cxxtqtbskqnfoxh.jpg",
        },
      ],
    },
    {
      review_id: 1275223,
      rating: 5,
      summary: "MY name is Trey",
      recommend: true,
      response: null,
      body: "My name is trey and i got a basketball game tommorrow",
      date: "2022-06-07T00:00:00.000Z",
      reviewer_name: "Trey",
      helpfulness: 1,
      photos: [
        {
          id: 2455209,
          url: "http://res.cloudinary.com/thejoebro/image/upload/v1654147335/o8v99cxxtqtbskqnfoxh.jpg",
        },
      ],
    },
    {
      review_id: 1275044,
      rating: 3,
      summary: "this is the summary for my reviewthis is the summary for my ",
      recommend: true,
      response: null,
      body: "this is the summary for my reviewthis is the summary for my reviewthis is the summary for my reviewthis is the summary for my reviewthis is the summary for my reviewthis is the summary for my review",
      date: "2022-06-02T00:00:00.000Z",
      reviewer_name: "kjrlkewfkjrlkewf",
      helpfulness: 1,
      photos: [
        {
          id: 2455111,
          url: "https://i.ibb.co/BZhVwjq/d50ba894d771.png",
        },
      ],
    },
    {
      review_id: 1275017,
      rating: 5,
      summary: "MY name is Trey",
      recommend: true,
      response: null,
      body: "My name is trey and i got a basketball game tommorrow",
      date: "2022-06-02T00:00:00.000Z",
      reviewer_name: "Trey",
      helpfulness: 2,
      photos: [
        {
          id: 2455107,
          url: "http://res.cloudinary.com/thejoebro/image/upload/v1654147335/o8v99cxxtqtbskqnfoxh.jpg",
        },
      ],
    },
    {
      review_id: 1274658,
      rating: 4,
      summary: "best puchars ever!",
      recommend: true,
      response: null,
      body: "lalalalla this is my review test bod plz work lesgo ",
      date: "2022-05-27T00:00:00.000Z",
      reviewer_name: "beep",
      helpfulness: 4,
      photos: [
        {
          id: 2454869,
          url: "https://i.ibb.co/KwG22K1/2f8bb554e3e7.png",
        },
        {
          id: 2454870,
          url: "https://i.ibb.co/YcX0cHj/1d939d11ef2f.png",
        },
        {
          id: 2454872,
          url: "https://i.ibb.co/jHBHfvm/37a8fa0c2476.png",
        },
        {
          id: 2454871,
          url: "https://i.ibb.co/WPwpWrS/879f70de945c.png",
        },
        {
          id: 2454873,
          url: "https://i.ibb.co/nP4KmLy/7005ac7ae83d.png",
        },
      ],
    },
    {
      review_id: 1274431,
      rating: 5,
      summary: "Lorem ipsum dolor sit amet.",
      recommend: true,
      response: null,
      body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce iaculis sollicitudin diam non rutrum. Mauris porttitor lacus in risus finibus laoreet. Donec ante ipsum, dapibus eget ligula nec, porta condimentum nibh. Duis ante dui, tempus nec arcu ut, feugiat fringilla nibh. Maecenas non bibendum nisl. Quisque nec tempor lacus, ac rhoncus nibh. Cras lacinia urna id elit venenatis hendrerit. Maecenas varius magna non velit pharetra laoreet. Sed iaculis, diam sed mollis cursus, quam tortor bibendum magna, vel blandit diam purus sed metus. Pellentesque lobortis non turpis et rutrum. Fusce scelerisque arcu a ornare lobortis.",
      date: "2022-05-23T00:00:00.000Z",
      reviewer_name: "Lorem Ipsum",
      helpfulness: 0,
      photos: [],
    },
    {
      review_id: 1136034,
      rating: 5,
      summary: "yes",
      recommend: true,
      response: null,
      body: "this review is going to be at least fifty characters if it's the last thing i do",
      date: "2022-02-26T00:00:00.000Z",
      reviewer_name: "doug",
      helpfulness: 8,
      photos: [],
    },
  ],
};
